Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rml.load_state_dict(torch.load("dirty_image_model.pt"))
rml.state_dict()  # the reloaded parameters of the model
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[16], line 1[0m
[0;32m----> 1[0m [43mrml[49m[38;5;241;43m.[39;49m[43mload_state_dict[49m[43m([49m[43mtorch[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mdirty_image_model.pt[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m)[49m
[1;32m      2[0m rml[38;5;241m.[39mstate_dict()  [38;5;66;03m# the reloaded parameters of the model[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/torch/nn/modules/module.py:1671[0m, in [0;36mModule.load_state_dict[0;34m(self, state_dict, strict)[0m
[1;32m   1666[0m         error_msgs[38;5;241m.[39minsert(
[1;32m   1667[0m             [38;5;241m0[39m, [38;5;124m'[39m[38;5;124mMissing key(s) in state_dict: [39m[38;5;132;01m{}[39;00m[38;5;124m. [39m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   1668[0m                 [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;124m'[39m[38;5;124m"[39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;124m'[39m[38;5;241m.[39mformat(k) [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m missing_keys)))
[1;32m   1670[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(error_msgs) [38;5;241m>[39m [38;5;241m0[39m:
[0;32m-> 1671[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m'[39m[38;5;124mError(s) in loading state_dict for [39m[38;5;132;01m{}[39;00m[38;5;124m:[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   1672[0m                        [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m, [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin(error_msgs)))
[1;32m   1673[0m [38;5;28;01mreturn[39;00m _IncompatibleKeys(missing_keys, unexpected_keys)

[0;31mRuntimeError[0m: Error(s) in loading state_dict for SimpleNet:
	Unexpected key(s) in state_dict: "fcube.vis". 
RuntimeError: Error(s) in loading state_dict for SimpleNet:
	Unexpected key(s) in state_dict: "fcube.vis". 

